### ISSUE TITLE
generated code ?

### ISSUE THREAD

**Issue by Youssef-Lehmam** [tpoisson/haxball-boenbot#14]
How to generate the code ?

**Comment by tpoisson** [comment]
Assuming you are familiar with `npm` commands : 

1. Clone code
2. Install dependencies : `npm ci`
3. Build project : `npm run build`
4. Generated code is now available in the `build` folder
5. Follow instructions : [https://github.com/tpoisson/haxball-boenbot#how-to-test](https://github.com/tpoisson/haxball-boenbot#how-to-test)
6. Enjoy!
